### PR TITLE
hotfix for ignored `--env` flag issue (#269)

### LINKED ISSUE #269: command line option -e is ignored when GO_ENV is defined in .env file
### Steps to Reproduce the Problem

In a dir with a .env containing `GO_ENV=development` , run 

  1. `soda migrate -e test`

### Expected Behavior

The `test` environment should be used when `-e test` arg is given.

### Actual Behavior

The `development` environment is used, ignoring the command line flag.

It's also surprising to me that the `.env` file will override `GO_ENV`. I.e. `GO_ENV=test soda migrate` will also defer to the `.env` file... is that intended?

### Info

macOS 10.13.6, using latest pop (git: 0596d299dc4e19f8639d15006e4984853e6c0087)

### PR DESCRIPTION
**Pull request by sio4**
Not fully sure if the issue happen again or if the previous patch does not fill all the cases. Anyway, the same issue happens again:

```console
$ soda reset -e test
pop v6.0.2

[POP] 2022/06/04 20:40:03 info - drop app_development (...)
Error: couldn't drop database app_development: error dropping...
```

#### Issue Description
Even though the `--env` (or short `-e`) flag is given, the command just follows the environment variable.

#### Root Cause
It seems like the issue was caused by confusing naming and the behavior of `PersistantPreRun` field of `cobra.Command` and `PersistentFlags()` function. I added a detailed comment on the code so easy to check later.

(One unrelated commit is also included :-)

Related: #282
Fixes #269

### CODE REVIEW

File: soda/cmd/root_integration_test.go [hunk 1]
```diff
@@ -7,27 +7,29 @@ import (
 	"github.com/stretchr/testify/require"
 )
 
-func Test_RootCmd_NoArg(t *testing.T) {
+func Test_RootCmd_Environtment(t *testing.T) {
```
Comment (stanislas-m) [inline soda/cmd/root_integration_test.go:10]:
```suggestion
func Test_RootCmd_Environment(t *testing.T) {
```

File: soda/cmd/root_integration_test.go [hunk 2]
```diff
@@ -7,27 +7,29 @@ import (
...
 	oldEnv := os.Getenv("GO_ENV")
 	defer os.Setenv("GO_ENV", oldEnv)
 
-	// Fallback on default env
 	r := require.New(t)
 	c := RootCmd
-	c.SetArgs([]string{})
+
+	// Fallback on default env
+	c.SetArgs([]string{"help"})
```
Comment (stanislas-m) [inline soda/cmd/root_integration_test.go:18]: `help` is already the default command, do you really need to change this?

File: soda/cmd/root_integration_test.go [hunk 3]
```diff
@@ -7,27 +7,29 @@ import (
...
 	err := c.Execute()
 	r.NoError(err)
 	r.Equal("development", env)
 
 	// Override with GO_ENV
-	c.SetArgs([]string{})
+	c.SetArgs([]string{"help"})
```
Comment (stanislas-m) [inline soda/cmd/root_integration_test.go:24]: `help` is already the default command, do you really need to change this?

**Comment by sio4** [comment]
Hi @stanislas-m! Thanks for the comment.

I added the explanation of the changed test more clearly (I think :-) and added commits to fix

* the typo on the test name, and more test condition
* fix for the Github action (recent windows runner has a memory allocation issue when race detector is on)

Please take a look at the commits and the last comment I added.

Thanks!

**Review by stanislas-m — APPROVED** [review]
