### PR TITLE
Fix 212

### LINKED ISSUE #212: Fix brakes add_foreign_key
## Description

The `fix` package blindly replaces `})` with `}`, unaware of context.

### Steps to Reproduce the Problem

```
add_foreign_key("domains", "domain_id", {"domains": ["id"]}, {
    "name": "fk_rules_domains",
    "on_delete": "CASCADE",
    "on_update": "CASCADE",
})
```

Run `buffalo db fix`, get this:

```
add_foreign_key("domains", "domain_id", {"domains": ["id"]}, {
    "name": "fk_rules_domains",
    "on_delete": "CASCADE",
    "on_update": "CASCADE",
}
```

### Expected Behavior

Don't introduce a syntax error. Also a check after the "fix" operation that the syntax of the result is still valid and roll the changes back otherwise.

### Actual Behavior

`fix` removes a `)` where it shouldn't.

#### Workaround

As a workaround, type `add_foreign_key` migrations (and similar) as follows:

```
add_foreign_key("domains", "domain_id", {"rules": ["id"]}, {
    "name": "fk_rules_domains",
    "on_delete": "CASCADE",
    "on_update": "CASCADE", })
```

I.e. don't let the `})` be on it's own line.

#### Cause

https://github.com/gobuffalo/pop/blob/7bb873077bba624e819348fe6ef605bc891b5069/fix/anko.go#L20-L22

This part is not implemented "context aware".

### PR DESCRIPTION
**Pull request by mclark4386**
Closes #212

### CODE REVIEW

**Comment by cimnine** [comment]
How does this fix work? When the condition on line 17 is true, how can the nested condition on line 19 become true? What am I missing here?

**Comment by mclark4386** [comment]
You are correct. I was a bit to quick on the draw and wasn't paying attention... the interesting part to me is that my tests all passed for me locally...

File: fix/anko.go [hunk 1]
```diff
@@ -12,13 +12,20 @@ func Anko(content string) (string, error) {
 	lines := strings.Split(content, "\n")
 
 	// fix create_table
-	for i, line := range lines {
+	in_create_table := false
```
Comment (stanislas-m) [inline fix/anko.go]: Please use the camelCase syntax, not the snake_case one. :)
