### PR TITLE
catch panic within transaction to complete rollback (fixes #748)

### LINKED ISSUE #748: pop.Connection.Transaction can leak connections
## Description

If a user's code panics within a [`pop.Connection.Transaction`](https://github.com/gobuffalo/pop/blob/main/connection.go#L150-L174) closure, `.Rollback` nor `.Commit` will not be called resulting in a leaked SQL connection.

### Steps to Reproduce the Problem

```go
func DoThing(conn *pop.Connection) {
    _ = conn.Transaction(func(tx *pop.Connection) error {
        panic("Oh no, this is probably due to a null pointer exception!")
    })
}
```

### Expected Behavior

`.Transaction` should `recover` panics and attempt to call `.Rollback` before re-panicking the error.

### Actual Behavior

A SQL connection is silently leaked. Depending on your connection pool setting, you might not even notice.

### Info

This issue is not specific to an OS and is observable on the latest `main` commit (4e72fd8f35449c084bd44fee9eedf64ebd2b62b4) as of writing

### PR DESCRIPTION
**Pull request by sio4**
`Connection.Transaction()` starts a transaction before executing a given inner function and then commits or rollback the transaction controlled by the return error value of the inner function. However, as reported in #748, it just exits without committing or rolling back the current transaction so the transaction (and lock status) could remain as open (it could depend on the behavior of the backing database engine).

The current behavior of the method is:

```
=== RUN   Test_Connection_Transaction
[POP] 2022/09/22 20:08:51 sql - --- BEGIN Transaction ---
--- FAIL: Test_Connection_Transaction (0.00s)
panic: handler panic [recovered]
	panic: handler panic
<...>
```

The fixed behavior by this PR is:

```
=== RUN   Test_Connection_Transaction
[POP] 2022/09/22 20:11:01 sql - --- BEGIN Transaction ---
[POP] 2022/09/22 20:11:01 sql - --- ROLLBACK Transaction (inner function panic) 
```

Additionally, this PR added `log(logging.SQL,...)` for begin, commit, and rollback actions so the transaction status could be easily observed along with SQL statements when the user enabled SQL logging.

fixes #748

### CODE REVIEW

File: connection.go [hunk 1]
```diff
@@ -151,21 +152,37 @@ func (c *Connection) Close() error {
 // returns an error then the transaction will be rolled back, otherwise the transaction
 // will automatically commit at the end.
 func (c *Connection) Transaction(fn func(tx *Connection) error) error {
-	return c.Dialect.Lock(func() error {
+	return c.Dialect.Lock(func() (err error) {
 		var dberr error
+
+		log(logging.SQL, "--- BEGIN Transaction ---")
```
Comment (sio4) [inline connection.go:158]: adding debugging log (logging.SQL) for transactions too.

File: connection.go [hunk 2]
```diff
@@ -151,21 +152,37 @@ func (c *Connection) Close() error {
...
+		defer func() {
+			if ex := recover(); ex != nil {
+				log(logging.SQL, "--- ROLLBACK Transaction (inner function panic) ---")
+				dberr = cn.TX.Rollback()
+				if dberr != nil {
+					err = fmt.Errorf("database error while inner panic rollback: %w", dberr)
+				}
+				err = fmt.Errorf("transaction was rolled back due to inner panic")
+			}
+		}()
```
Comment (sio4) [inline connection.go:173]: the interrupted transaction should be rolled back when inner function panic

**Review by sio4 — COMMENTED** [review]
comment on the code
