### PR TITLE
prevent empty query to be executed

### LINKED ISSUE #560: Running an empty RawQuery causes a panic
## Description

Running an empty RawQuery causes a panic.

### Steps to Reproduce the Problem

```
sqlite, _ := pop.NewConnection(&pop.ConnectionDetails{
	URL: "sqlite3://" + filepath.Join(os.TempDir(), x.NewUUID().String()) + ".sql?mode=memory&_fk=true",
})
_ = sqlite.Open()
sqlite.RawQuery("").Exec()
```

### Expected Behavior

No panic.

### Actual Behavior

A panic happens:

```
% go test -tags sqlite .
--- FAIL: TestMigrations (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x46c74f2]

goroutine 10 [running]:
testing.tRunner.func1.1(0x4d86060, 0x5973aa0)
        /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc0001c58c0)
        /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:943 +0x3f9
panic(0x4d86060, 0x5973aa0)
        /usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:969 +0x166
github.com/gobuffalo/pop/v5.(*Model).TableName(0x0, 0x0, 0x0)
        /Users/foobar/go/src/github.com/gobuffalo/pop/model.go:79 +0x52
github.com/gobuffalo/pop/v5.(*sqlBuilder).buildColumns(0xc0001fb868, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/foobar/go/src/github.com/gobuffalo/pop/sql_builder.go:218 +0x65
github.com/gobuffalo/pop/v5.(*sqlBuilder).buildSelectSQL(0xc0001fb868, 0x0, 0x0)
        /Users/foobar/go/src/github.com/gobuffalo/pop/sql_builder.go:102 +0x40
github.com/gobuffalo/pop/v5.(*sqlBuilder).compile(0xc0001fb868)
        /Users/foobar/go/src/github.com/gobuffalo/pop/sql_builder.go:87 +0x369
github.com/gobuffalo/pop/v5.(*sqlBuilder).String(...)
        /Users/foobar/go/src/github.com/gobuffalo/pop/sql_builder.go:57
github.com/gobuffalo/pop/v5.Query.ToSQL(0xc0000333b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/foobar/go/src/github.com/gobuffalo/pop/query.go:206 +0x1db
github.com/gobuffalo/pop/v5.(*Query).Exec.func1(0xbfaffeb74d0bc090, 0xcc6278)
        /Users/foobar/go/src/github.com/gobuffalo/pop/executors.go:25 +0x91
github.com/gobuffalo/pop/v5.(*Connection).timeFunc(0xc0007a4900, 0x4f07ee0, 0x4, 0xc000079cd0, 0x30, 0x4ded6e0)
        /Users/foobar/go/src/github.com/gobuffalo/pop/connection.go:231 +0x50
github.com/gobuffalo/pop/v5.(*Query).Exec(0xc000079e70, 0xc0000333b0, 0x0)
        /Users/foobar/go/src/github.com/gobuffalo/pop/executors.go:24 +0x6a
github.com/ory/kratos/persistence/sql/migratest.TestMigrations(0xc0001c58c0)
        /Users/foobar/go/src/github.com/ory/kratos/persistence/sql/migratest/migration_test.go:74 +0x2f7
testing.tRunner(0xc0001c58c0, 0x4f7c148)
        /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
        /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:1042 +0x357
FAIL    github.com/ory/kratos/persistence/sql/migratest 0.429s
```

### Info

```
github.com/gobuffalo/pop/v5 v5.1.3
```

### PR DESCRIPTION
**Pull request by sio4**
Empty `Query` should not be executed.

fixes #560

### CODE REVIEW

File: executors.go [hunk 1]
```diff
@@ -20,10 +20,16 @@ func (c *Connection) Reload(model interface{}) error {
 	})
 }
 
+// TODO: consider merging the following two methods.
```
Comment (sio4) [inline executors.go:23]: can these two methods be merged to be based on `ExecWithCount()`? by just dropping the int return value?
It could be better to manage but the only issue is the elapsed time calculated by `timeFunc` could be slightly different :-)

File: executors.go [hunk 2]
```diff
@@ -36,6 +42,10 @@ func (q *Query) ExecWithCount() (int, error) {
 	count := int64(0)
 	return int(count), q.Connection.timeFunc("Exec", func() error {
 		sql, args := q.ToSQL(nil)
+		if sql == "" {
+			return fmt.Errorf("empty query")
+		}
```
Comment (sio4) [inline executors.go:47]: if the `sql`, the result of `ToSQL()` is empty, just abort the execution. This is the main part of this PR.

File: query.go [hunk 3]
```diff
@@ -213,6 +213,10 @@ func Q(c *Connection) *Query {
 // from the `Model` passed in.
 func (q Query) ToSQL(model *Model, addColumns ...string) (string, []interface{}) {
 	sb := q.toSQLBuilder(model, addColumns...)
+	// nil model is allowed only when if RawSQL is provided.
+	if model == nil && (q.RawSQL == nil || q.RawSQL.Fragment == "") {
+		return "", nil
+	}
```
Comment (sio4) [inline query.go:219]: logically, if the given Model is nil and also there is no RawSQL, then the query is invalid (or not prepared). no need to call the builder.

File: query_test.go [hunk 4]
```diff
@@ -386,3 +386,22 @@ func Test_ToSQL_RawQuery(t *testing.T) {
...
 }
+
+func Test_RawQuery_Empty(t *testing.T) {
+	Debug = true
+	defer func() { Debug = false }()
+
+	t.Run("EmptyQuery", func(t *testing.T) {
+		r := require.New(t)
+		transaction(func(tx *Connection) {
+			r.Error(tx.Q().Exec())
```
Comment (sio4) [inline query_test.go:397]: totally empty query

File: query_test.go [hunk 5]
```diff
@@ -386,3 +386,22 @@ func Test_ToSQL_RawQuery(t *testing.T) {
...
+		})
+	})
+
+	t.Run("EmptyRawQuery", func(t *testing.T) {
+		r := require.New(t)
+		transaction(func(tx *Connection) {
+			r.Error(tx.RawQuery("").Exec())
```
Comment (sio4) [inline query_test.go:404]: this is also an empty query too :-)

File: sql_builder.go [hunk 6]
```diff
@@ -83,7 +82,12 @@ func (sq *sqlBuilder) compile() {
 				}
 				sq.sql = sq.Query.RawSQL.Fragment
 			}
+			sq.args = sq.Query.RawSQL.Arguments
 		} else {
+			if sq.Model == nil {
+				sq.err = fmt.Errorf("sqlBuilder.compile() called but no RawSQL and Model specified")
+				return
```
Comment (sio4) [inline sql_builder.go:89]: 1. prevent execution of the following calls that require Model or RawQuery
2. set error message to the caller can see it

now the caller will not call the builder, but to make it safer.
