### PR TITLE
Fix Anko converter

### LINKED ISSUE #217: old fizz migrations borked
## Description

Version 4.6.8 does not seem to correctly interpret old-style migrations.

### Steps to Reproduce the Problem

Try to `soda migrate up` with this migration:
```
create_table("users", func(t) {
	t.Column("id", "uuid", {"primary": true})
	t.Column("organization_id", "uuid", {})
	t.Column("first_name", "string", {})
	t.Column("last_name", "string", {})
	t.Column("email", "string", {})
	t.Column("cognito_id", "string", {"null": true})
})

add_index("users", "organization_id",{})
```

### Expected Behavior

The migration would be run and a table would be created.

### Actual Behavior

Ker-splat: 
```
/Volumes/source/golang/bin/soda migrate up -e development -c /Users/geoff/.beacon-people/database.yml
v4.6.8

> create_users
[WARN] migrations/20180125210618_create_organizations.up.fizz uses an old fizz syntax. please use
create_table("organizations") {
	t.Column("id", "uuid", {"primary": true})
	t.Column("name", "string", {})
})

0.0454 seconds
dumped schema for beacon_people
Error: error processing migrations/20180125210618_create_organizations.up.fizz: could not fizz the migration migrations/20180125210618_create_organizations.up.fizz: line 4: no prefix parse function for ) found
Usage:
  soda migrate up [flags]

Flags:
  -h, --help   help for up

Global Flags:
  -c, --config string   The configuration file you would like to use.
  -d, --debug           Use debug/verbose mode
  -e, --env string      The environment you want to run migrations against. Will use $GO_ENV if set. (default "development")
  -p, --path string     Path to the migrations folder (default "./migrations")

error processing migrations/20180125210618_create_organizations.up.fizz: could not fizz the migration migrations/20180125210618_create_organizations.up.fizz: line 4: no prefix parse function for ) found
```

### Info

I'm on MacOS 10.13.6; I'm using pop/soda on the command line. If I fall back to 4.6.6 the migration runs (as do its sibling migrations.)

### PR DESCRIPTION
**Pull request by stanislas-m**
Fixes #217

### CODE REVIEW

File: fix/anko.go [hunk 1]
```diff
@@ -12,30 +13,35 @@ func Anko(content string) (string, error) {
...
-	}
-
-	// fix raw
-	for i, line := range lines {
-		tl := strings.TrimSpace(line)
-		if strings.HasPrefix(tl, "raw(") {
+			// skip already converted create_table
+			if strings.Contains(line, ", func(t) {") {
+				// fix create_table
+				line = strings.Replace(line, ", func(t) {", ") {", -1)
```
Comment (mclark4386) [inline fix/anko.go]: Since you are re-doing this, it would be nice to use regex.ReplaceAllString() so that it'll not care about any whitespace. (We didn't have `, func`, but `,func` and it wouldn't work.

Comment (stanislas-m) [reply fix/anko.go]: Done. :)

File: fix/anko.go [hunk 2]
```diff
@@ -12,30 +14,36 @@ func Anko(content string) (string, error) {
...
+					if strings.HasPrefix(tl, "})") {
+						line = "}"
+						break
+					} else if strings.HasPrefix(tl, "}") {
+						break
+					}
+					i++
+					line = lines[i]
+					tl = strings.TrimSpace(line)
+					if l == i {
```
Comment (mclark4386) [inline fix/anko.go]: you are checking for overflow after trying to access an item past the length of the array on 38.

File: fix/fixtures/pass/0001_with_raw_backticks.anko.fizz [hunk 3]
```diff
@@ -8,9 +8,18 @@ create_table("users", func(t) {
...
 
-create_table("domains") {
+create_table("domains", func(t) {
+  t.Column("id","uuid",{"primary":true})
+})
+
+create_table("sodas", func(t) {
   t.Column("id","uuid",{"primary":true})
 }
+)
```
Comment (mclark4386) [inline fix/fixtures/pass/0001_with_raw_backticks.anko.fizz]: I'm clearly just missing it since the tests are passing, but at some point you are  going to have to explain to me how it's catching this straggler seeing as it looks to me as though it would have moved out of the create_table logic the line before.

**Comment by mclark4386** [comment]
Thanks for changing that to a RegEx btw^^

File: fix/anko.go [hunk 4]
```diff
@@ -12,30 +14,40 @@ func Anko(content string) (string, error) {
...
+				waitParen := false
+				for {
+					if strings.HasPrefix(tl, "})") {
+						line = "}"
+						break
+					} else if strings.HasPrefix(tl, "}") {
+						// Now, we have to make sure to match the missing ")"
+						waitParen = true
+					} else if waitParen && strings.HasPrefix(tl, ")") {
+						break
```
Comment (mclark4386) [inline fix/anko.go]: Need to clear line before breaking and then we are good!

File: fix/anko.go [hunk 5]
```diff
@@ -30,12 +30,13 @@ func Anko(content string) (string, error) {
 				waitParen := false
 				for {
 					if strings.HasPrefix(tl, "})") {
-						line = "}"
+						line = tl[2:]
```
Comment (mclark4386) [inline fix/anko.go]: in the case that tl is "})" then tl[2:] will be "". I think you were going for `"}" + tl[2:]`
