### PR TITLE
Fix bad log filtering with default logger

### LINKED ISSUE #232: Logging SQL statements during migration when debug flag not set
## Description

PR https://github.com/gobuffalo/pop/pull/186 introduced a change to the way logging is done.  In particular this added a `SQL` logging level which is lower than `DEBUG` level.  However, when running migrations the SQL statements will print even if the debug flag is not set.

The particular statements that I think may need to be reworked are here: https://github.com/gobuffalo/pop/blob/master/logger.go#L31-L33

### Steps to Reproduce the Problem

You'll need to have UP migrations available for this to work.  Then run a command like this:

```
DB_HOST=localhost DB_PORT=5432 DB_NAME=test_db go run ../gobuffalo/pop/soda/main.go -e test migrate -c ./config/database.yml -p ./migrations up
```

You ought to see output like:

screen shot 2018-08-31 at 10 26 48 am

### Expected Behavior

When the debug flag is not set in the `soda` command I'd expect to see no SQL statements during a migration.  When it I do set the debug flag I'd expect to see only `DEBUG` level logs.  I wonder if it would make sense to have a verbose flag that prints out the `SQL` level logs.  But I'd settle for just hiding them in the debug flag.

I get the expected behavior if I change the code lines to look like:

```go
if !Debug {
    return
}
if lvl > logging.Debug {
    return
}
```

### Info

I'm running this on:
- OS: MacOSX 10.13.6
- Go: 1.10
- Pop: v4.7.0
- Not using Buffalo, just Pop.

### PR DESCRIPTION
**Pull request by stanislas-m**
Fixes #232

### CODE REVIEW

File: logger.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ var defaultLogger = func(lvl logging.Level, s string, args ...interface{}) {
 		Log(s, args...)
 		return
 	}
-	if !Debug && lvl > logging.Debug {
+	if !Debug && lvl <= logging.Debug {
```
Comment (kteb) [inline logger.go]: I'm not sure about this changement the problem should be somewhere else because we have: 
SQL = 0
Debug = 1
Info = 2
Warn = 3 

so the lvl > logging.Debug sounds right.

I would also suggest to do it in an other way (but I'm not sure of the impact (except for readability) :

```go
    switch lvl {
    case logging.SQL:
        if len(args) > 0 {
			xargs := make([]string, len(args))
			for i, a := range args {
				switch a.(type) {
				case string:
					xargs[i] = fmt.Sprintf("%q", a)
				default:
					xargs[i] = fmt.Sprintf("%v", a)
				}
			}
			s = fmt.Sprintf("%s - %s | %s", lvl, s, xargs)
                } else {
                        s = fmt.Sprintf("%s - %s", lvl, s)
                }
    default:
        if !Debug && lvl <> logging.Debug { 
                return
        }
        s = fmt.Sprintf(s, args...)
	s = fmt.Sprintf("%s - %s", lvl, s)
    }
```

Comment (stanislas-m) [reply logger.go]: It's not that easy to read, but the new condition is correct. We need to trim logs from levels lower or equal than debug, in non-debug mode.

It's a simple boolean logic mistake.
